{{! Copyright (c) Avanade. Licensed under the MIT License. See https://github.com/Avanade/Beef }}
/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Data;
using Beef.Data.Database;
using {{Root.Company}}.{{Root.AppName}}.Common.Entities;

namespace {{Root.Company}}.{{Root.AppName}}.Business.Data
{
    public partial class {{Tvp}}Data
    {
        public partial class DbMapper
        {
            /// <summary>
            /// Creates a <see cref="TableValuedParameter"/> for the <paramref name="list"/>.
            /// </summary>
            /// <param name="list">The entity list.</param>
            /// <returns>The Table-Valued Parameter.</returns>
            public TableValuedParameter CreateTableValuedParameter(IEnumerable<{{Tvp}}> list)
            {        
                var dt = new DataTable();
{{#each UdtColumns}}
                dt.Columns.Add("{{Name}}", typeof({{DbColumn.DotNetType}}));
{{/each}}

                var tvp = new TableValuedParameter("[{{Schema}}].[udt{{Name}}List]", dt);
                AddToTableValuedParameter(tvp, list);
                return tvp;
            }
        }
    }
}

#nullable restore