{{! Copyright (c) Avanade. Licensed under the MIT License. See https://github.com/Avanade/Beef }}
/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable
#pragma warning disable IDE0005 // Using directive is unnecessary; are required depending on code-gen options

using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Beef;
using Beef.Entities;
{{#ifeq Root.EntityUsing 'Common' 'All'}}
using {{Root.Company}}.{{Root.AppName}}.Common.Entities;
{{/ifeq}}
{{#ifeq Root.EntityUsing 'Business' 'All'}}
using {{Root.Company}}.{{Root.AppName}}.Business.Entities;
{{/ifeq}}
{{#ifval Root.RefDataNamespace}}
using RefDataNamespace = {{Root.RefDataNamespace}};
{{/ifval}}
{{#ifval Root.RefDataBusNamespace}}
using RefDataNamespace = {{Root.RefDataBusNamespace}};
{{/ifval}}

namespace {{Root.Company}}.{{Root.AppName}}.Business
{
    /// <summary>
    /// Defines the {{{EntityNameSeeComments}}} business functionality.
    /// </summary>
    public partial interface I{{Name}}Manager{{#if GenericWithT}}<T>{{/if}}
    {
{{#each IManagerOperations}}
  {{#unless @first}}

  {{/unless}} 
        /// <summary>
        /// {{{SummaryText}}}
        /// </summary>
  {{#each Parameters}}
        /// <param name="{{ArgumentName}}">{{{SummaryText}}}</param>
  {{/each}}
  {{#if HasReturnValue}}
        /// <returns>{{{ReturnText}}}</returns>
  {{/if}}
        {{{OperationTaskReturnType}}} {{Name}}Async({{#each Parameters}}{{#unless @first}}, {{/unless}}{{ParameterType}} {{ArgumentName}}{{/each}});
{{/each}}
    }
}

#pragma warning restore IDE0005
#nullable restore