/*
 * This file is automatically generated; any changes will be lost. 
 */

#nullable enable
#pragma warning disable IDE0005 // Using directive is unnecessary; are required depending on code-gen options

using System;
using System.Collections.Generic;
using System.Data;
using System.Text;
using System.Threading.Tasks;
{{#ifval Root.RefDataNamespace}}
using RefDataNamespace = {{Root.RefDataNamespace}};
{{/ifval}}
{{#ifval Root.RefDataBusNamespace}}
using RefDataBusNamespace = {{Root.RefDataBusNamespace}};
{{/ifval}}

namespace {{Root.Company}}.{{Root.AppName}}.Business.Data
{
    /// <summary>
    /// Provides the <b>ReferenceData</b> data access.
    /// </summary>
    public partial interface IReferenceDataData
    {
{{#each RefDataEntities}}
  {{#unless @first}}

  {{/unless}}
        /// <summary>
        /// Gets all the {{seecomments RefDataQualifiedEntityName}} items.
        /// </summary>
        /// <returns>The {{seecomments RefDataQualifiedEntityCollectionName}}.</returns>
        Task<{{RefDataQualifiedEntityCollectionName}}> {{Name}}GetAllAsync();
{{/each}}
    }
}

#pragma warning restore IDE0005
#nullable restore